### ISSUE TITLE
云盘正常使用，让创建管理员账号，，我如何恢复

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#214]
如图，我正常使用云盘，但是今天登录上显示我初始创建管理员的页面，这个情况出现很多次，每次我都是恢复服务器备份
![PixPin_2024-07-05_11-09-36](https://github.com/jamebal/jmal-cloud-view/assets/106538519/3d2c3e3f-8552-4f65-895a-05c546d2cfe9)

**Comment by jamebal** [comment]
从什么开始的? 刷新浏览器或者重启服务有用吗

**Comment by Xiaoph123** [comment]
我的数据都还再，但是为什么会跳到创建管理员的页面，我尝试了重新启动jmalcloud和服务器，都不行

**Comment by Xiaoph123** [comment]
> 从什么开始的? 刷新浏览器或者重启服务有用吗

今天，第一次出现这个情况忘记了是什么时候发生的

**Comment by jamebal** [comment]
在这个界面按F12, 看看这个预览数据
<img width="858" alt="截屏2024-07-05 11 24 13" src="https://github.com/jamebal/jmal-cloud-view/assets/49510841/e3aab57a-ed21-4052-bcd5-3787de4ef824">

**Comment by Xiaoph123** [comment]
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/a2ba361d-c9e2-47ac-bad2-c052a54989f8)

**Comment by jamebal** [comment]
使用这个命令看看输出结果: 
```shell
docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").user.find().count();'
```

**Comment by Xiaoph123** [comment]
```
[root@rainyun-16dwllwu jmal-cloud-server]# docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").user.find().count();'
MongoDB shell version v4.4.29
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("cf6e98cb-bee6-42e2-8537-cc3acbee83cf") }
MongoDB server version: 4.4.29
1
[root@rainyun-16dwllwu jmal-cloud-server]# 

```

**Comment by jamebal** [comment]
显示创建管理员的逻辑是: 查询是否存在用户
根据你给出的信息: 数据库里确实是有用户的, 但是界面上没查出来

**Comment by jamebal** [comment]
是恢复服务器备份就好了, 然后过一会又出现创建管理员了吗

**Comment by Xiaoph123** [comment]
恢复备份后，能管用个1到2个星期左右，然后就又出现了，很奇怪

**Comment by jamebal** [comment]
直接通过ip:端口访问试试

**Comment by jamebal** [comment]
或者在命令行里执行, 看输出结果
```shell
curl -l https://demo.jmalx.com:21904/api/public/has_user
```
把 https://demo.jmalx.com:21904 换成你自己的网盘地址

**Comment by Xiaoph123** [comment]
端口号访问：
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/6ecb494e-e3fa-4430-b8fc-2b7f004ae2dc)

**Comment by jamebal** [comment]
> 端口号访问： ![image](https://private-user-images.githubusercontent.com/106538519/345995960-6ecb494e-e3fa-4430-b8fc-2b7f004ae2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTIyMjAsIm5iZiI6MTcyMDE1MTkyMCwicGF0aCI6Ii8xMDY1Mzg1MTkvMzQ1OTk1OTYwLTZlY2I0OTRlLWUzZmEtNDQzMC1iOGZjLTJiN2YwMDRhZTJkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwMzU4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTZhNzM0NzYwMTMxOTBhZjNiNmY1YjEzMTc3ZDZjNWNhYTgwMTk3MzhlYTdhNGVhODhkZDAxYzliMGEyNWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9kNI9gJsI1d5AsIlgZtluAHY05Zv9sN7Jo0fitC8V0w)

通过ip:端口正常, 通过域名访问就出现创建管理员是吗?

**Comment by Xiaoph123** [comment]
> > 端口号访问： ![image](https://private-user-images.githubusercontent.com/106538519/345995960-6ecb494e-e3fa-4430-b8fc-2b7f004ae2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTIyMjAsIm5iZiI6MTcyMDE1MTkyMCwicGF0aCI6Ii8xMDY1Mzg1MTkvMzQ1OTk1OTYwLTZlY2I0OTRlLWUzZmEtNDQzMC1iOGZjLTJiN2YwMDRhZTJkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwMzU4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTZhNzM0NzYwMTMxOTBhZjNiNmY1YjEzMTc3ZDZjNWNhYTgwMTk3MzhlYTdhNGVhODhkZDAxYzliMGEyNWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9kNI9gJsI1d5AsIlgZtluAHY05Zv9sN7Jo0fitC8V0w)
> 
> 通过ip:端口正常, 通过域名访问就出现创建管理员是吗?

端口访问jmalchoud是默认的登录页面，这个默认登录页面我修改了图标和名称，通过域名访问是创建管理员页面

**Comment by jamebal** [comment]
在命令行里执行以下两条命令, 看输出结果
 
- 1
```shell
curl -l https://demo.jmalx.com:21904/api/public/has_user
```
- 2
```shell
https://demo.jmalx.com:21904/api/public/website/record
```
把 https://demo.jmalx.com:21904 换成你自己的网盘地址

**Comment by Xiaoph123** [comment]
域名结果：
{"code":0,"message":true,"data":true,"count":1}

ip结果：
{"code":0,"message":true,"data":true,"count":1}

**Comment by jamebal** [comment]
<img width="903" alt="截屏2024-07-05 13 01 39" src="https://github.com/jamebal/jmal-cloud-view/assets/49510841/a27e3c93-b659-4570-805b-7c82f354b50c">
网页上count是0, curl 返回的count是1

**Comment by jamebal** [comment]
<img width="697" alt="截屏2024-07-05 13 03 20" src="https://github.com/jamebal/jmal-cloud-view/assets/49510841/b1d19f2b-9c6a-4856-8f8d-ca4bad2a1676">

钩上停用缓存试试

**Comment by Xiaoph123** [comment]
> <img alt="截屏2024-07-05 13 03 20" width="697" src="https://private-user-images.githubusercontent.com/49510841/346006845-b1d19f2b-9c6a-4856-8f8d-ca4bad2a1676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTYxODgsIm5iZiI6MTcyMDE1NTg4OCwicGF0aCI6Ii80OTUxMDg0MS8zNDYwMDY4NDUtYjFkMTlmMmItOWM2YS00ODU2LThmOGQtY2E0YmFkMmExNjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NzdkMDk4ZDI3ZDRmZGI1N2JmZjJhZTgzNDU1YWI4YmZlYzM3MzA4ZWIzNWZlOGI5OWRiOTU3MzU2N2FjOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtcKna6RSDAWqgMcHihG2ENktOELufaKVnaVjSCd01U">
> 钩上停用缓存试试

清缓存的方法我试过了不行

**Comment by Xiaoph123** [comment]
网页上count是1，但是登录不上
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/228234af-a60d-4af5-815a-5d700627f55d)

**Comment by Xiaoph123** [comment]
有解决方案吗，如果没有的话，我只能恢复备份了

**Comment by jamebal** [comment]
恢复备份是恢复mongodb的备份吗

**Comment by Xiaoph123** [comment]
> 恢复备份是恢复mongodb的备份吗

不是，是整个服务器的备份

**Comment by Xiaoph123** [comment]
重新加载数据库的命令是那个我试一下

**Comment by jamebal** [comment]
你提到修改过图标和名称, 但是界面上没有显示, 执行这条命令看看数据有没有相关配置
```shell
docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").websiteSetting.find();'
```

**Comment by Xiaoph123** [comment]
[root@rainyun-16dwllwu ~]# docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").websiteSetting.find();'
MongoDB shell version v4.4.29
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("e0a36027-d9d3-451a-91cf-926412076b95") }
MongoDB server version: 4.4.29
[root@rainyun-16dwllwu ~]#

**Comment by jamebal** [comment]
> [root@rainyun-16dwllwu ~]# docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").websiteSetting.find();' MongoDB shell version v4.4.29 connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb Implicit session: session { "id" : UUID("e0a36027-d9d3-451a-91cf-926412076b95") } MongoDB server version: 4.4.29 [root@rainyun-16dwllwu ~]#

没有任何配置, 数据没了?

**Comment by Xiaoph123** [comment]
> > [root@rainyun-16dwllwu ~]# docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").websiteSetting.find();' MongoDB shell version v4.4.29 connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb Implicit session: session { "id" : UUID("e0a36027-d9d3-451a-91cf-926412076b95") } MongoDB server version: 4.4.29 [root@rainyun-16dwllwu ~]#
> 
> 没有任何配置, 数据没了?

这个就是我奇怪的地方，数据怎么会没有呢

**Comment by Xiaoph123** [comment]
我的文件都在，目录结构都完整的

**Comment by jamebal** [comment]
也就是恢复备份后，1到2个星期左右mongodb里面的数据就没了

**Comment by Xiaoph123** [comment]
今天下午6点我将恢复备份，在此期间可以测试一下什么原因

**Comment by jamebal** [comment]
看看这个命令的结果
```shell
docker exec -it jmalcloud_mongodb mongo --eval 'db.getSiblingDB("jmalcloud").fileDocument.count();'
```

**Comment by Xiaoph123** [comment]
> 也就是恢复备份后，1到2个星期左右mongodb里面的数据就没了

是的，会不会被攻击了？
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/ad303e86-32b8-4d36-bff3-a376bf1e7735)

**Comment by jamebal** [comment]
进入mongodb看看有没有别的东西:
1. 进入mognodb
```shell
docker exec -it jmalcloud_mongodb mongo
```
2. 查看数据库
```shell
show dbs;
```

**Comment by Xiaoph123** [comment]
``` shell
[root@rainyun-16dwllwu ~]# docker exec -it jmalcloud_mongodb mongo
MongoDB shell version v4.4.29
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("5ee2aa9c-6495-40da-9d31-82c2cfcda74e") }
MongoDB server version: 4.4.29
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	https://docs.mongodb.com/
Questions? Try the MongoDB Developer Community Forums
	https://community.mongodb.com
---
The server generated these startup warnings when booting: 
        2024-07-05T11:56:48.370+08:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
        2024-07-05T11:56:48.370+08:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
        2024-07-05T11:56:48.370+08:00: /sys/kernel/mm/transparent_hugepage/defrag is 'always'. We suggest setting it to 'never'
---
> show dbs;
READ__ME_TO_RECOVER_YOUR_DATA  0.000GB
admin                          0.000GB
config                         0.000GB
jmalcloud                      0.001GB
local                          0.000GB
> 

```

**Comment by Xiaoph123** [comment]
这个readme  我被勒索了吗这是

**Comment by jamebal** [comment]
> 这个readme 我被勒索了吗这是

是的, 里面的数据都被删除了

**Comment by Xiaoph123** [comment]
有什么办法能恢复吗

**Comment by jamebal** [comment]
默认的docker-compose.yml, 是没有设置mongodb帐号密码的, 你应该没有暴露mongodb的端口吧

**Comment by jamebal** [comment]
看是服务器被黑了, 还是只是mongodb被黑了

**Comment by Xiaoph123** [comment]
> 默认的docker-compose.yml, 是没有设置mongodb帐号密码的, 你应该没有暴露mongodb的端口吧

没有暴露mongodb的端口

**Comment by Xiaoph123** [comment]
> 看是服务器被黑了, 还是只是mongodb被黑了

这个我需要怎么排查

**Comment by Xiaoph123** [comment]
如果是mongodb被黑怎么办

**Comment by jamebal** [comment]
没有暴露mongodb的端口证明mongodb无法从外部访问

**Comment by jamebal** [comment]
查查服务器ssh登录日志, 看看有没有其他人登录

**Comment by jamebal** [comment]
> 如果是mongodb被黑怎么办

恢复备份, 之后加上帐号密码

**Comment by Xiaoph123** [comment]
> > 如果是mongodb被黑怎么办
> 
> 恢复备份, 之后加上帐号密码

具体如何做，怎么添加账号和密码

**Comment by Xiaoph123** [comment]
> 查查服务器ssh登录日志, 看看有没有其他人登录

ssh被暴力了

**Comment by jamebal** [comment]
> > > 如果是mongodb被黑怎么办
> > 
> > 
> > 恢复备份, 之后加上帐号密码
> 
> 具体如何做，怎么添加账号和密码

手动创建用户。首先，进入 MongoDB 容器：
```shell
docker exec -it jmalcloud_mongodb mongo
```
然后在 MongoDB shell 中手动创建管理员用户：example改成自己的密码
```shell
use admin;
db.createUser({
  user: "root",
  pwd: "example",
  roles: [ { role: "root", db: "admin" } ]
})
```
修改后的 docker-compose.yml 文件中的`MONGODB_URI`:
```shell
...省略
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/jmalcloud?authSource=admin"  # 更新MongoDB URI以包含用户名和密码
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms256m -Xmx1024m"
    volumes:
...省略
```

**Comment by Xiaoph123** [comment]
改完密码登不上了
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/d3c3efa7-7b8a-4cd6-8839-6c03a1c6f391)

**Comment by jamebal** [comment]
修改完docker-compose.yml 还要执行下`docker-compose up -d`

**Comment by Xiaoph123** [comment]
执行了，还是不行

**Comment by jamebal** [comment]
测试下帐号密码: 进入 MongoDB 容器
```shell
docker exec -it jmalcloud_mongodb mongo admin
```
验证帐号密码
```
db.auth('root','example');
```

**Comment by Xiaoph123** [comment]
账号密码是正确的
[root@rainyun-16dwllwu jmal-cloud-server]# docker exec -it jmalcloud_mongodb mongo admin
MongoDB shell version v4.4.29
connecting to: mongodb://127.0.0.1:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("98dd8b5e-1b9d-41ab-ae92-c9ab7cef3843") }
MongoDB server version: 4.4.29
---
The server generated these startup warnings when booting: 
        2024-07-05T17:18:30.693+08:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
        2024-07-05T17:18:30.693+08:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
        2024-07-05T17:18:30.693+08:00: /sys/kernel/mm/transparent_hugepage/defrag is 'always'. We suggest setting it to 'never'
---
> db.auth('root','xxxxxxxxxx');
1
>

**Comment by jamebal** [comment]
看看jmalcloud_server到日志: 
```shell
docker logs -300f jmalcloud_server
```

**Comment by Xiaoph123** [comment]
重新启动后报错
```
[root@rainyun-16dwllwu jmal-cloud-server]# ./jc.sh restart
WARN[0000] /mnt/redcatdata/jmal-cloud-server/docker-compose.yml: `version` is obsolete 
[+] Stopping 5/5
 ✔ Container jmalcloud_nginx    Stopped                                                                                                                                                                      0.3s 
 ✔ Container jmalcloud_mongodb  Stopped                                                                                                                                                                      0.4s 
 ✔ Container jmalcloud_server   Stopped                                                                                                                                                                     10.4s 
 ✔ Container jmalcloud_office   Stopped                                                                                                                                                                     10.3s 
 ✔ Container jmalcloud_drawio   Stopped                                                                                                                                                                      0.3s 
WARN[0000] /mnt/redcatdata/jmal-cloud-server/docker-compose.yml: `version` is obsolete 
[+] Running 5/5
 ✔ Container jmalcloud_office   Started                                                                                                                                                                      0.4s 
 ✔ Container jmalcloud_drawio   Started                                                                                                                                                                      0.4s 
 ✔ Container jmalcloud_mongodb  Started                                                                                                                                                                      0.5s 
 ✔ Container jmalcloud_server   Started                                                                                                                                                                      1.6s 
 ✔ Container jmalcloud_nginx    Started                                                                                                                                                                      0.7s 
[错误] 启动失败，反馈给开发者: https://github.com/jamebal/jmal-cloud-view/issues
[root@rainyun-16dwllwu jmal-cloud-server]# 
```

**Comment by jamebal** [comment]
docker logs -f jmalcloud_server

**Comment by Xiaoph123** [comment]
```
Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-256, userName='root', source='admin', password=<hidden>, mechanismProperties=<hidden>}
	at com.mongodb.internal.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:270)
	at com.mongodb.internal.connection.SaslAuthenticator.lambda$authenticate$0(SaslAuthenticator.java:86)
	at com.mongodb.internal.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:277)
	at com.mongodb.internal.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:59)
	at com.mongodb.internal.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:57)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.authenticate(InternalStreamConnectionInitializer.java:206)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.finishHandshake(InternalStreamConnectionInitializer.java:86)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:216)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:55)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.open(DefaultConnectionPool.java:647)
	at com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openWithConcurrencyLimit(DefaultConnectionPool.java:993)
	at com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openOrGetAvailable(DefaultConnectionPool.java:934)
	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:203)
	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:192)
	at com.mongodb.internal.connection.DefaultServer.getConnection(DefaultServer.java:96)
	at com.mongodb.internal.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:186)
	at com.mongodb.client.internal.ClientSessionBinding$SessionBindingConnectionSource.getConnection(ClientSessionBinding.java:196)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:144)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
	at com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableRead$4(SyncOperationHelper.java:189)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateReadWithRetries$12(SyncOperationHelper.java:292)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableRead(SyncOperationHelper.java:194)
	at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableRead(SyncOperationHelper.java:176)
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:193)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:153)
	at com.mongodb.internal.operation.CountDocumentsOperation.execute(CountDocumentsOperation.java:134)
	at com.mongodb.internal.operation.CountDocumentsOperation.execute(CountDocumentsOperation.java:41)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCount(MongoCollectionImpl.java:227)
	at com.mongodb.client.internal.MongoCollectionImpl.countDocuments(MongoCollectionImpl.java:197)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$doExactCount$15(MongoTemplate.java:1226)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:601)
	... 160 common frames omitted
Caused by: java.lang.IllegalArgumentException: Prohibited character at position 10
	at com.mongodb.internal.authentication.SaslPrep.saslPrep(SaslPrep.java:90)
	at com.mongodb.internal.authentication.SaslPrep.saslPrepStored(SaslPrep.java:55)
	at com.mongodb.internal.connection.ScramShaAuthenticator$ScramShaSaslClient.getAuthenicationHash(ScramShaAuthenticator.java:333)
	at com.mongodb.internal.connection.ScramShaAuthenticator$ScramShaSaslClient.computeClientFinalMessage(ScramShaAuthenticator.java:227)
	at com.mongodb.internal.connection.ScramShaAuthenticator$ScramShaSaslClient.evaluateChallenge(ScramShaAuthenticator.java:166)
	at com.mongodb.internal.connection.SaslAuthenticator.lambda$authenticate$0(SaslAuthenticator.java:67)
	... 193 common frames omitted
Exception in thread "pool-2-thread-1" org.springframework.data.mongodb.ClientSessionException: state should be: open
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:143)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2997)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:603)
	at org.springframework.data.mongodb.core.MongoTemplate.doExactCount(MongoTemplate.java:1225)
	at org.springframework.data.mongodb.core.MongoTemplate.doCount(MongoTemplate.java:1194)
	at org.springframework.data.mongodb.core.MongoTemplate$ExistsCallback.doInCollection(MongoTemplate.java:3106)
	at org.springframework.data.mongodb.core.MongoTemplate$ExistsCallback.doInCollection(MongoTemplate.java:3089)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:601)
	at org.springframework.data.mongodb.core.MongoTemplate.exists(MongoTemplate.java:848)
	at org.springframework.data.mongodb.core.MongoTemplate.exists(MongoTemplate.java:833)
	at com.jmal.clouddisk.service.impl.MenuService.lambda$init$0(MenuService.java:63)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:109)
	at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:103)
	at com.mongodb.internal.connection.SingleServerCluster.selectServer(SingleServerCluster.java:46)
	at com.mongodb.internal.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:116)
	at com.mongodb.client.internal.ClientSessionBinding.getConnectionSource(ClientSessionBinding.java:128)
	at com.mongodb.client.internal.ClientSessionBinding.getReadConnectionSource(ClientSessionBinding.java:92)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:144)
	at com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableRead$4(SyncOperationHelper.java:189)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateReadWithRetries$12(SyncOperationHelper.java:292)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableRead(SyncOperationHelper.java:194)
	at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableRead(SyncOperationHelper.java:176)
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:193)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:153)
	at com.mongodb.internal.operation.CountDocumentsOperation.execute(CountDocumentsOperation.java:134)
	at com.mongodb.internal.operation.CountDocumentsOperation.execute(CountDocumentsOperation.java:41)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCount(MongoCollectionImpl.java:227)
	at com.mongodb.client.internal.MongoCollectionImpl.countDocuments(MongoCollectionImpl.java:197)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$doExactCount$15(MongoTemplate.java:1226)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:601)
	... 18 more

```

**Comment by jamebal** [comment]
错误显示mognodb认证失败: 
重建容器试试: 
```shell
docker-compose down
```
```shell
docker-compose up -d
```

**Comment by jamebal** [comment]
看日志是否还是这个问题: docker logs -f jmalcloud_server

**Comment by jamebal** [comment]
可能是密码里有特殊字符, 需要把MONGODB_URI转译一下: 

例如，如果你的 MongoDB 连接字符串是这样：
```shell
mongodb://username:password@host:port/database
```

如果用户名或密码中包含特殊字符，如 @, :, /，则需要将这些字符进行 URL 编码。
举个例子，如果用户名是 user@name，密码是 pass/word，那么连接字符串应该是：
```
mongodb://user%40name:pass%2Fword@host:port/database
```

**Comment by Xiaoph123** [comment]
经过URL编码后就可以了感谢

**Comment by Xiaoph123** [comment]
onlyoffice打开出现报错怎么解决
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/fe1f8bf2-54e2-41dd-bcb0-def97622ef3e)

![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/965271c0-2d91-4bc1-aed2-d559318901d4)

**Comment by jamebal** [comment]
零时办法，重启office服务
