### ISSUE TITLE
部署之后新建文件失败

### ISSUE THREAD

**Issue by Hehaooguoo** [jamebal/jmal-cloud-view#24]
您好 使用jc.sh 部署后，创建新文件夹失败。不知道问题在哪里。

**Comment by Hehaooguoo** [comment]
==> /var/log/onlyoffice/documentserver/nginx.error.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2022-08-26T03:28:12.000] [ERROR] nodeJS - error downloadFile:url=http://10.28.29.70:7070/api/file/admin%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx?jmal-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJXRUIiLCJpc3MiOiJTZXJ2aWNlIiwidXNlcm5hbWUiOiJhZG1pbiJ9.YoWM_EnKxYkFu1WC_jeibP09BHDG_dM_1Cm7rDqMgg4;attempt=1;code:null;connect:null;(id=1661484489000-63083dc988b9cdc985f2cba1)
Error: Error response: statusCode:500; headers:{"server":"nginx/1.21.5","date":"Fri, 26 Aug 2022 03:28:11 GMT","content-type":"application/json;charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","content-disposition":"inline;filename=f.txt"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-08-26T03:28:13.023] [ERROR] nodeJS - error downloadFile:url=http://10.28.29.70:7070/api/file/admin%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx?jmal-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJXRUIiLCJpc3MiOiJTZXJ2aWNlIiwidXNlcm5hbWUiOiJhZG1pbiJ9.YoWM_EnKxYkFu1WC_jeibP09BHDG_dM_1Cm7rDqMgg4;attempt=2;code:null;connect:null;(id=1661484489000-63083dc988b9cdc985f2cba1)
Error: Error response: statusCode:500; headers:{"server":"nginx/1.21.5","date":"Fri, 26 Aug 2022 03:28:13 GMT","content-type":"application/json;charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","content-disposition":"inline;filename=f.txt"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-08-26T03:28:14.044] [ERROR] nodeJS - error downloadFile:url=http://10.28.29.70:7070/api/file/admin%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx?jmal-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJXRUIiLCJpc3MiOiJTZXJ2aWNlIiwidXNlcm5hbWUiOiJhZG1pbiJ9.YoWM_EnKxYkFu1WC_jeibP09BHDG_dM_1Cm7rDqMgg4;attempt=3;code:null;connect:null;(id=1661484489000-63083dc988b9cdc985f2cba1)
Error: Error response: statusCode:500; headers:{"server":"nginx/1.21.5","date":"Fri, 26 Aug 2022 03:28:14 GMT","content-type":"application/json;charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","content-disposition":"inline;filename=f.txt"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

这是jmalcloud_office 的错误日志。不知道是不是这里的问题

**Comment by Hehaooguoo** [comment]
==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2022-08-26T05:27:19.117] [WARN] nodeJS - Express server starting...
[2022-08-26T05:27:19.121] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-08-26T05:27:19.281] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.0.0. Build: 132
[2022-08-26T05:28:28.448] [WARN] nodeJS - Express server starting...
[2022-08-26T05:28:28.452] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-08-26T05:28:28.590] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.0.0. Build: 132

**Comment by Hehaooguoo** [comment]
我查了日志 发现在新建文件夹时调用的是 upload-folder 是不是应该调用 new_folder ？

**Comment by jamebal** [comment]
更新下镜像
`docker pull registry.cn-guangzhou.aliyuncs.com/jmalcloud/jmalcloud`
`./jc.sh update`

**Comment by Hehaooguoo** [comment]
更新时报了一个新的错误。  在页面上，新建文件夹还是不成功。
From https://gitee.com/jmal/jmal-cloud-server
   80db4a1..028f781  master     -> origin/master
   80db4a1..4c62fc6  develop    -> origin/develop
 * [new tag]         1.0        -> 1.0
 * [new tag]         2.0        -> 2.0
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.8      -> 2.1.8
 * [new tag]         2.2.33     -> 2.2.33
 * [new tag]         v2.2.34    -> v2.2.34
 * [new tag]         v2.3.0     -> v2.3.0
HEAD is now at 028f781 🐛修复用户名缓存问题
Already up-to-date.
WARN[0000] The "RESOURCE_DB_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "RESOURCE_DB_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "RESOURCE_DB_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "RESOURCE_FILE_PATH" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/jmalcloud/files/: empty section between colons
[OK] 更新完成

新建文件时的日志如下：
![image](https://user-images.githubusercontent.com/26889857/187070713-38d10674-1489-4342-a708-7dc7ea610e79.png)

**Comment by Hehaooguoo** [comment]
我尝试再次更新 ./jc.sh update ，成功了。 但是之前存储的数据全部丢失了。 这样还是有问题  ./jc.sh update 会导致数据全部丢失。

**Comment by Hehaooguoo** [comment]
但是创建文件失败的问题已经获得了修复。
