### ISSUE TITLE
启动项目后登录报错

### ISSUE THREAD

**Issue by userAmani** [jamebal/jmal-cloud-view#25]
2022-09-01 11:26:50 |ERROR |http-nio-8088-exec-1 |CommonExceptionHandler.java:28 |com.jmal.clouddisk.exception.CommonExceptionHandler |null
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.put(UnboundedLocalCache.java:371)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.put(UnboundedLocalCache.java:366)

**Comment by jamebal** [comment]
请提供更多的日志信息

**Comment by userAmani** [comment]
![image](https://user-images.githubusercontent.com/29222146/187826961-a412e020-db6d-47f3-9463-d5fa20c40d68.png)
正常启动，但是点击登录的时候报错

**Comment by jamebal** [comment]
更新下应用`./jc.sh update`
